### ISSUE TITLE
French phone number starting with 07 or +337 are not working

### ISSUE THREAD

**Issue by monisnap-jeremie** [acoutts/flutter_libphonenumber#86]
Hello 👋 

I am facing an issue with french phone number starting with `+33 7` or `07`.

It seems this is not valid.

I am using Flutter with `flutter_libphonenumber: 2.5.0` package, `pod "PhoneNumberKit", '3.8.0'` on iOS.

Is it a shared issue or am I doing anything wrong?

**Comment by monisnap-jeremie** [comment]
Hi @jlethuau,

We have added a temporary hot fix in our code :

```dart
    if (isValid == false && countryCode == 'FR') {
      isValid = RegExp(r'(6|7|06|07)\d{8}').hasMatch(phoneNumber);
    }
```

Considering `isValid` as a boolean that is set after `libphonenumber.parse()` call and `countryCode` as the value set by the user when filling its phone number.

We hope to have an update someday 😅

**Comment by acoutts** [comment]
I've just pushed v2.7.0 with the latest phone number kit / libphonenumber, can you please try again on this version?

**Comment by monisnap-jeremie** [comment]
@acoutts thank you for your answer.

It still doesn’t seem to work on our side.

To make sure we are aligned regarding the versions we are using, here are the details:

**pubspec.yaml**

```
flutter_libphonenumber: ^2.7.0
```

**pubspec.lock**

```
flutter_libphonenumber:
  version: "2.7.0"
flutter_libphonenumber_android:
  version: "2.0.0"
flutter_libphonenumber_darwin:
  version: "2.1.0"
```

**Podfile.lock**

```
PODS:
  - PhoneNumberKit/PhoneNumberKitCore (4.2.1)

DEPENDENCIES:
  - flutter_libphonenumber_darwin (from `.symlinks/plugins/flutter_libphonenumber_darwin/darwin`)

EXTERNAL SOURCES:
  flutter_libphonenumber_darwin:
    :path: ".symlinks/plugins/flutter_libphonenumber_darwin/darwin"
```

Let me know if you need additional information.
